ability_refresh: 60
api_key_blue: J4yQNXgqvH4WgqeKBnwdI0gNACpujJGiciA_IhOeHx4
api_key_red: Fg10u9ZDu9j9xnpTvTEMnxT6tUtt5eLFxBeaR7f1Xw8
app.contact.dns.domain: mycaldera.caldera
app.contact.dns.socket: 0.0.0.0:8853
app.contact.ftp.host: 0.0.0.0
app.contact.ftp.port: 2222
app.contact.ftp.pword: caldera
app.contact.ftp.server.dir: ftp_dir
app.contact.ftp.user: caldera_user
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.slack.api_key: SLACK_TOKEN
app.contact.slack.bot_id: SLACK_BOT_ID
app.contact.slack.channel_id: SLACK_CHANNEL_ID
app.contact.tcp: 0.0.0.0:7010
app.contact.tunnel.ssh.host_key_file: REPLACE_WITH_KEY_FILE_PATH
app.contact.tunnel.ssh.host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE
app.contact.tunnel.ssh.socket: 0.0.0.0:8022
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: s4ndc4t!
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
app.frontend.api_base_url: http://100.74.219.96:8888
auth.login.handler.module: default
crypt_salt: Aotr7GVqTCbezfHHBQlQlFgXrfKmm1zQrKu7culovMc
encryption_key: FCe8lQ5n_yhn45_fHnEfD3iK2ySenGlQtHS-cASdVoo
exfil_dir: /tmp/caldera
host: 0.0.0.0
objects.planners.default: atomic
plugins:
- access
- compass
- debrief
- fieldmanual
- manx
- response
- sandcat
- stockpile
- training
port: 8888
reachable_host_traits:
- remote.host.fqdn
- remote.host.ip
reports_dir: /tmp
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.19
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.8.0
users:
  blue:
    blue: QJLxq6-qcWtrerY9aKPY7iZQmGKK8c-7K1gtrFUwZGY
  red:
    red: lkS0XVcqFEXJCxjNj4hVghu8v9EIxxgWxJnJa2jElA0
